import { z } from "zod";

export type MusicalToolRisk = "read" | "playback" | "library-mutation" | "file-mutation";

export type MusicalToolDefinition = {
  name: string;
  title: string;
  description: string;
  inputSchema: z.ZodObject<z.ZodRawShape>;
  risk: MusicalToolRisk;
  modelVisible: boolean;
};

const emptyInput = z.object({});
const nullableInteger = z.number().int().nullable();
const optionalLimit = z.number().int().min(1).max(100).optional();
const optionalArtist = z.string().min(1).optional();
const optionalSentimentWeight = z.number().finite().min(0).max(0.3).optional();
const trackIdsInput = z.object({ trackIds: z.array(z.string().min(1)).max(500) });

export const musicalTools = [
  {
    name: "get_player_state",
    title: "Get Player State",
    description: "Read Musical's current playback state.",
    inputSchema: emptyInput,
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_library",
    title: "Get Library",
    description: "Return the indexed album library.",
    inputSchema: emptyInput,
    risk: "read",
    modelVisible: true,
  },
  {
    name: "search_library",
    title: "Search Library",
    description: "Search albums and tracks by title, artist, year, genre, or file path.",
    inputSchema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_track_lyrics",
    title: "Get Track Lyrics",
    description: "Read lyrics saved in a track tag.",
    inputSchema: z.object({ trackId: z.string().min(1) }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_track_lyrics_analysis",
    title: "Get Track Lyrics Analysis",
    description:
      "Read block-level and track-level Japanese sentiment analysis for a track's saved lyrics.",
    inputSchema: z.object({ trackId: z.string().min(1) }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_search_index_status",
    title: "Get Search Index Status",
    description:
      "Report whether Musical's persistent local semantic-search index is ready or stale.",
    inputSchema: emptyInput,
    risk: "read",
    modelVisible: true,
  },
  {
    name: "build_search_index",
    title: "Build Search Index",
    description:
      "Build or incrementally refresh Musical's local semantic-search index. The multilingual embedding model is downloaded on first use and cached locally.",
    inputSchema: emptyInput,
    risk: "library-mutation",
    modelVisible: true,
  },
  {
    name: "search_tracks",
    title: "Search Tracks",
    description:
      "Search track metadata and saved lyrics with local multilingual semantic or hybrid matching and optional coverage-weighted sentiment similarity.",
    inputSchema: z.object({
      query: z.string().min(1),
      mode: z.enum(["semantic", "hybrid"]).optional(),
      target: z.enum(["all", "lyrics", "metadata"]).optional(),
      lyricsOnly: z.boolean().optional(),
      favoriteOnly: z.boolean().optional(),
      minRating: z.number().int().min(1).max(5).optional(),
      genres: z.array(z.string().min(1)).max(50).optional(),
      excludeTrackIds: z.array(z.string().min(1)).max(500).optional(),
      sentimentWeight: optionalSentimentWeight,
      limit: optionalLimit,
    }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "recommend_tracks",
    title: "Recommend Tracks",
    description:
      "Recommend tracks for a natural-language mood using local semantic and coverage-weighted sentiment similarity over metadata and saved lyrics, with diversity and duration controls.",
    inputSchema: z.object({
      prompt: z.string().min(1),
      favoriteOnly: z.boolean().optional(),
      minRating: z.number().int().min(1).max(5).optional(),
      genres: z.array(z.string().min(1)).max(50).optional(),
      avoidTrackIds: z.array(z.string().min(1)).max(500).optional(),
      durationMinutes: z.number().int().min(1).max(1440).optional(),
      maxTracksPerArtist: z.number().int().min(1).max(20).optional(),
      sentimentWeight: optionalSentimentWeight,
      limit: optionalLimit,
    }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "search_lyrics_by_mood",
    title: "Search Lyrics by Mood",
    description:
      "Find songs from the meaning, emotion, scene, or remembered line in saved lyrics without changing playback. Apply bounded topic-aware ranking and collapse duplicate lyrical variants only for explicit grief, elegy, mourning, or bereavement prompts, or prompts combining loss/separation with sorrow. A generic sad-song prompt, generic mood, and relativeToCurrent remain unchanged. Use search_library for an exact title or artist alone. For lyrics similar to the current track or brighter/darker than it, set relativeToCurrent. Put only the desired lyrical meaning, scene, or emotion in prompt, not spoken playback commands.",
    inputSchema: z.object({
      prompt: z.string().trim().min(1).max(500),
      moodStrength: z.enum(["subtle", "balanced", "strong"]).optional(),
      favoriteOnly: z.boolean().optional(),
      minRating: z.number().int().min(1).max(5).optional(),
      genres: z.array(z.string().min(1)).max(50).optional(),
      artist: z.string().trim().min(1).optional(),
      excludeTrackIds: z.array(z.string().min(1)).max(500).optional(),
      relativeToCurrent: z.enum(["similar", "brighter", "darker"]).optional(),
      limit: z.number().int().min(1).max(20).optional(),
    }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "play_lyrics_by_mood",
    title: "Play Lyrics by Mood",
    description:
      "Find songs from the meaning, emotion, or scene in saved lyrics, set the resulting queue, and start playback in one operation. Apply bounded topic-aware ranking and collapse duplicate lyrical variants only for explicit grief, elegy, mourning, or bereavement prompts, or prompts combining loss/separation with sorrow. A generic sad-song prompt, generic mood, and relativeToCurrent remain unchanged. Use play_search for an exact title, album, or artist. Set relativeToCurrent for lyrics similar to the current track or brighter/darker than it; use limit: 1 for one song and durationMinutes: 30 for about 30 minutes. Put only the desired lyrical meaning, scene, or emotion in prompt, not spoken playback commands.",
    inputSchema: z.object({
      prompt: z.string().trim().min(1).max(500),
      moodStrength: z.enum(["subtle", "balanced", "strong"]).optional(),
      favoriteOnly: z.boolean().optional(),
      minRating: z.number().int().min(1).max(5).optional(),
      genres: z.array(z.string().min(1)).max(50).optional(),
      artist: z.string().trim().min(1).optional(),
      avoidTrackIds: z.array(z.string().min(1)).max(500).optional(),
      relativeToCurrent: z.enum(["similar", "brighter", "darker"]).optional(),
      durationMinutes: z.number().int().min(1).max(1440).optional(),
      maxTracksPerArtist: z.number().int().min(1).max(20).optional(),
      limit: z.number().int().min(1).max(100).optional(),
    }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "get_library_summary",
    title: "Get Library Summary",
    description: "Return artist, album, track, favorite, and scan summary counts.",
    inputSchema: emptyInput,
    risk: "read",
    modelVisible: true,
  },
  {
    name: "list_albums",
    title: "List Albums",
    description: "List albums, optionally filtered by artist name.",
    inputSchema: z.object({ artist: optionalArtist, limit: optionalLimit }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "list_tracks",
    title: "List Tracks",
    description: "List tracks, optionally filtered by album ID or artist name.",
    inputSchema: z.object({
      albumId: z.string().min(1).optional(),
      artist: optionalArtist,
      limit: optionalLimit,
    }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_album",
    title: "Get Album",
    description: "Return one album by ID.",
    inputSchema: z.object({ albumId: z.string().min(1) }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_track",
    title: "Get Track",
    description: "Return one track by ID.",
    inputSchema: z.object({ trackId: z.string().min(1) }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "find_artist",
    title: "Find Artist",
    description: "Find likely artist matches by name, allowing simple spelling and spacing differences.",
    inputSchema: z.object({ name: z.string().min(1), limit: optionalLimit }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "find_album",
    title: "Find Album",
    description: "Find likely album matches by album name and optional artist.",
    inputSchema: z.object({ name: z.string().min(1), artist: optionalArtist, limit: optionalLimit }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_queue",
    title: "Get Queue",
    description: "Read the current playback queue.",
    inputSchema: emptyInput,
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_recently_played",
    title: "Get Recently Played",
    description: "Return tracks recently published by the active Musical player session.",
    inputSchema: z.object({ limit: optionalLimit }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "get_favorites",
    title: "Get Favorites",
    description: "Return tracks marked as favorites.",
    inputSchema: z.object({ limit: optionalLimit }),
    risk: "read",
    modelVisible: true,
  },
  {
    name: "play",
    title: "Play",
    description: "Start or resume playback.",
    inputSchema: emptyInput,
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "pause",
    title: "Pause",
    description: "Pause playback.",
    inputSchema: emptyInput,
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "toggle_playback",
    title: "Toggle Playback",
    description: "Toggle play and pause.",
    inputSchema: emptyInput,
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "next_track",
    title: "Next Track",
    description: "Skip to the next track.",
    inputSchema: emptyInput,
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "previous_track",
    title: "Previous Track",
    description: "Skip to the previous track.",
    inputSchema: emptyInput,
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "seek",
    title: "Seek",
    description: "Seek to a playback time in seconds.",
    inputSchema: z.object({ time: z.number().finite().min(0) }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "set_volume",
    title: "Set Volume",
    description: "Set volume from 0 to 1.",
    inputSchema: z.object({ volume: z.number().finite().min(0).max(1) }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "set_shuffle",
    title: "Set Shuffle",
    description: "Enable or disable shuffle.",
    inputSchema: z.object({ enabled: z.boolean().optional(), isShuffle: z.boolean().optional() }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "set_repeat",
    title: "Set Repeat",
    description: "Set repeat mode.",
    inputSchema: z.object({
      mode: z.enum(["off", "all", "one"]).optional(),
      repeatMode: z.enum(["off", "all", "one"]).optional(),
    }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "play_album",
    title: "Play Album",
    description: "Play an album by ID.",
    inputSchema: z.object({ albumId: z.string().min(1) }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "play_track",
    title: "Play Track",
    description: "Play a track by ID, optionally within an album.",
    inputSchema: z.object({ trackId: z.string().min(1), albumId: z.string().min(1).optional() }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "play_artist",
    title: "Play Artist",
    description: "Start playback for an artist by artist ID or name.",
    inputSchema: z.object({ artistId: z.string().min(1) }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "play_search",
    title: "Play Search",
    description: "Start playback from a natural search phrase by picking the best matching album, artist, or track.",
    inputSchema: z.object({ query: z.string().min(1) }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "set_queue",
    title: "Set Queue",
    description: "Replace the playback queue with the given track IDs.",
    inputSchema: trackIdsInput.extend({
      currentTrackId: z.string().min(1).optional(),
      play: z.boolean().optional(),
    }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "clear_queue",
    title: "Clear Queue",
    description: "Clear the playback queue.",
    inputSchema: emptyInput,
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "select_album",
    title: "Select Album",
    description: "Select an album in the Musical UI.",
    inputSchema: z.object({ albumId: z.string().min(1) }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "select_track",
    title: "Select Track",
    description: "Select a track in the Musical UI.",
    inputSchema: z.object({ trackId: z.string().min(1) }),
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "refresh_library",
    title: "Refresh Library",
    description: "Ask the Musical UI to reload the indexed library.",
    inputSchema: emptyInput,
    risk: "playback",
    modelVisible: true,
  },
  {
    name: "scan_music_folder",
    title: "Scan Music Folder",
    description: "Scan a local music folder and rebuild the indexed library.",
    inputSchema: z.object({ folderPath: z.string().min(1) }),
    risk: "library-mutation",
    modelVisible: true,
  },
  {
    name: "create_playlist",
    title: "Create Playlist",
    description: "Create a Musical playlist.",
    inputSchema: z.object({ name: z.string().min(1) }),
    risk: "library-mutation",
    modelVisible: true,
  },
  {
    name: "add_track_to_playlist",
    title: "Add Track To Playlist",
    description: "Add a track to a Musical playlist.",
    inputSchema: z.object({ playlistId: z.string().min(1), trackId: z.string().min(1) }),
    risk: "library-mutation",
    modelVisible: true,
  },
  {
    name: "delete_playlist",
    title: "Delete Playlist",
    description: "Delete a Musical playlist and its cached artwork.",
    inputSchema: z.object({ playlistId: z.string().min(1) }),
    risk: "library-mutation",
    modelVisible: true,
  },
  {
    name: "create_playlist_from_album",
    title: "Create Playlist From Album",
    description: "Create a Musical playlist from an album.",
    inputSchema: z.object({
      albumId: z.string().min(1),
      name: z.string().min(1),
    }),
    risk: "library-mutation",
    modelVisible: true,
  },
  {
    name: "update_album_tags",
    title: "Update Album Tags",
    description: "Write album-wide tag values to files in an album.",
    inputSchema: z.object({
      albumId: z.string().min(1),
      albumTitle: z.string(),
      albumArtist: z.string(),
      artist: z.string(),
      year: nullableInteger,
      genre: z.string(),
    }),
    risk: "file-mutation",
    modelVisible: true,
  },
  {
    name: "update_track_tags",
    title: "Update Track Tags",
    description: "Write tag values to one track file.",
    inputSchema: z.object({
      trackId: z.string().min(1),
      title: z.string(),
      artist: z.string(),
      albumTitle: z.string(),
      year: nullableInteger,
      genre: z.string(),
      trackNumber: nullableInteger,
      discNumber: nullableInteger,
    }),
    risk: "file-mutation",
    modelVisible: true,
  },
  {
    name: "update_track_artwork",
    title: "Update Track Artwork",
    description: "Write artwork from a local image path to the track's file.",
    inputSchema: z.object({ trackId: z.string().min(1), artworkPath: z.string().min(1) }),
    risk: "file-mutation",
    modelVisible: true,
  },
  {
    name: "update_playlist_artwork",
    title: "Update Playlist Artwork",
    description: "Copy artwork from a local image path next to the playlist file.",
    inputSchema: z.object({ playlistId: z.string().min(1), artworkPath: z.string().min(1) }),
    risk: "file-mutation",
    modelVisible: true,
  },
  {
    name: "add_favorite",
    title: "Add Favorite",
    description: "Mark a track as favorite while preserving its rating.",
    inputSchema: z.object({ trackId: z.string().min(1) }),
    risk: "library-mutation",
    modelVisible: true,
  },
  {
    name: "remove_favorite",
    title: "Remove Favorite",
    description: "Remove a track from favorites while preserving its rating.",
    inputSchema: z.object({ trackId: z.string().min(1) }),
    risk: "library-mutation",
    modelVisible: true,
  },
  {
    name: "update_track_user_state",
    title: "Update Track User State",
    description: "Set Musical-only favorite and rating for a track.",
    inputSchema: z.object({
      trackId: z.string().min(1),
      isFavorite: z.boolean(),
      rating: z.number().int().min(1).max(5).nullable(),
    }),
    risk: "library-mutation",
    modelVisible: true,
  },
] satisfies MusicalToolDefinition[];
